apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-guestbook-jbs
spec:
  ingressClassName: nginx
  rules:
  - host: guestbook.jbs.codeandski.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook-ui
            port:
              number: 80/TCP